# Generated by Django 4.0.4 on 2022-06-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_discription', models.CharField(max_length=200)),
                ('item_number', models.IntegerField()),
            ],
        ),
    ]
